/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CategoryDetail, RecipeItem } from './types';

export const CATEGORIES: CategoryDetail[] = [
  {
    id: 'beef',
    name: 'Beef',
    badge: 'RICH & SAVORY',
    tagline: 'Bold spices, marinades, and crusts.',
    description: 'Recommended spices and rubs for enhancing beef dishes, from steaks to slow-cooked roasts.',
    image: '/src/assets/images/beef_seasoning_1784062685307.jpg',
    seasonings: [
      {
        id: 'smoked_paprika',
        name: 'Smoked Paprika',
        category: 'beef',
        profile: 'Earthy & Sweet',
        description: 'Adds a deep, woodsy flavor and rich red color. Perfect for dry rubs on brisket or short ribs.',
        iconName: 'Flame',
        iconBgColor: 'bg-secondary-container',
        iconTextColor: 'text-on-secondary-container',
      },
      {
        id: 'rosemary',
        name: 'Rosemary',
        category: 'beef',
        profile: 'Piney & Aromatic',
        description: 'A classic pairing for steaks and roasts. Best used fresh, sprigged over hot butter during basting.',
        iconName: 'Leaf',
        iconBgColor: 'bg-tertiary-container',
        iconTextColor: 'text-on-tertiary',
      },
      {
        id: 'coarse_black_pepper',
        name: 'Coarse Black Pepper',
        category: 'beef',
        profile: 'Sharp & Pungent',
        description: 'Essential for crust formation on grilled steaks. Provides a sharp bite that cuts through rich fat.',
        iconName: 'Sparkles',
        iconBgColor: 'bg-surface-variant',
        iconTextColor: 'text-on-surface-variant',
      },
      {
        id: 'garlic_powder',
        name: 'Garlic Powder',
        category: 'beef',
        profile: 'Savory Base',
        description: 'Distributes savory notes evenly without burning at high temperatures like fresh minced garlic might.',
        iconName: 'Droplet',
        iconBgColor: 'bg-[#ffecb3]',
        iconTextColor: 'text-[#ff6f00]',
      },
    ],
  },
  {
    id: 'seafood',
    name: 'Fish & Seafood',
    badge: 'LIGHT & BRIGHT',
    tagline: 'Citrus, herbs, and delicate blends.',
    description: 'Delicate seasonings that respect and elevate the natural ocean flavors of premium catch.',
    image: '/src/assets/images/fish_seafood_1784062694000.jpg',
    seasonings: [
      {
        id: 'dill',
        name: 'Fresh Dill',
        category: 'seafood',
        profile: 'Herbal & Anise',
        description: 'Provides a clean, feathery aroma and subtle citrus undertones that complement trout and salmon.',
        iconName: 'LeafyGreen',
        iconBgColor: 'bg-primary-container',
        iconTextColor: 'text-on-primary-container',
      },
      {
        id: 'lemon_zest',
        name: 'Lemon Zest',
        category: 'seafood',
        profile: 'Citrus & Bright',
        description: 'Delivers an instant burst of clean acidity and essential oils, cutting through fatty fish.',
        iconName: 'Sun',
        iconBgColor: 'bg-amber-100',
        iconTextColor: 'text-amber-700',
      },
      {
        id: 'sea_salt_flakes',
        name: 'Maldon Sea Salt',
        category: 'seafood',
        profile: 'Clean Salinity',
        description: 'Adds a crunchy, delicate texture and pops of salt that let clean fish flavors shine.',
        iconName: 'Snowflake',
        iconBgColor: 'bg-sky-100',
        iconTextColor: 'text-sky-700',
      },
      {
        id: 'cayenne_pepper',
        name: 'Cayenne Pepper',
        category: 'seafood',
        profile: 'Mild Heat',
        description: 'Lends a quick, sharp warmth that works beautifully in blackened rub coatings.',
        iconName: 'FlameKindling',
        iconBgColor: 'bg-red-100',
        iconTextColor: 'text-red-700',
      },
    ],
  },
  {
    id: 'greens',
    name: 'Leafy Greens',
    badge: 'FRESH & TANGY',
    tagline: 'Dressings, toasted seeds, and acids.',
    description: 'Bright dressings, crunch profiles, and mineral seasonings to lift dark and crisp leafy greens.',
    image: '/src/assets/images/leafy_greens_1784062701760.jpg',
    seasonings: [
      {
        id: 'balsamic_vinegar',
        name: 'Balsamic Glaze',
        category: 'greens',
        profile: 'Acidic & Sweet',
        description: 'Rich, syrupy and sweet-tart. Turns a simple bowl of arugula or spinach into a culinary highlight.',
        iconName: 'Wine',
        iconBgColor: 'bg-purple-100',
        iconTextColor: 'text-purple-800',
      },
      {
        id: 'toasted_sesame',
        name: 'Toasted Sesame',
        category: 'greens',
        profile: 'Nutty & Rich',
        description: 'Adds an inviting roasty fragrance and microscopic crunchy bursts to massaged kale or spinach.',
        iconName: 'Boxes',
        iconBgColor: 'bg-yellow-100',
        iconTextColor: 'text-yellow-800',
      },
      {
        id: 'dijon_mustard',
        name: 'Dijon Mustard',
        category: 'greens',
        profile: 'Sharp Emulsifier',
        description: 'The creamy, spicy backbone required to lock oil and vinegar together into a unified, silky dressing.',
        iconName: 'CupSoda',
        iconBgColor: 'bg-orange-100',
        iconTextColor: 'text-orange-800',
      },
      {
        id: 'nutritional_yeast',
        name: 'Nutritional Yeast',
        category: 'greens',
        profile: 'Savory & Umami',
        description: 'Provides a vegan cheesy flavor, loaded with savory depth, ideal for dressing raw caesar salads.',
        iconName: 'Database',
        iconBgColor: 'bg-green-100',
        iconTextColor: 'text-green-800',
      },
    ],
  },
  {
    id: 'root_veg',
    name: 'Root Vegetables',
    badge: 'WARM & EARTHY',
    tagline: 'Warm spices, glazes, and robust herbs.',
    description: 'Flavors that caramelize during roasting, enriching the native sweetness of autumn harvests.',
    image: '/src/assets/images/root_vegetables_1784062711149.jpg',
    seasonings: [
      {
        id: 'thyme',
        name: 'Fresh Thyme',
        category: 'root_veg',
        profile: 'Woodsy & Piney',
        description: 'Its tiny leaves hold up beautifully to the high oven heat needed to caramelize starch-rich roots.',
        iconName: 'TreePine',
        iconBgColor: 'bg-emerald-100',
        iconTextColor: 'text-emerald-800',
      },
      {
        id: 'maple_syrup',
        name: 'Pure Maple Syrup',
        category: 'root_veg',
        profile: 'Woody Sweetness',
        description: 'Drizzled on carrots or parsnips in the last 10 minutes of baking to create a glassy, crispy lacquer.',
        iconName: 'Soup',
        iconBgColor: 'bg-amber-100',
        iconTextColor: 'text-amber-800',
      },
      {
        id: 'cumin',
        name: 'Ground Cumin',
        category: 'root_veg',
        profile: 'Smoky & Earthy',
        description: 'Provides a grounded, warm contrast that balances out the intense sweetness of yams and squashes.',
        iconName: 'Earth',
        iconBgColor: 'bg-stone-200',
        iconTextColor: 'text-stone-800',
      },
      {
        id: 'nutmeg',
        name: 'Freshly Grated Nutmeg',
        category: 'root_veg',
        profile: 'Aromatic Warmth',
        description: 'A tiny pinch unlocks a festive, deeply comforting flavor in mashed sweet potato or roasted pumpkin.',
        iconName: 'Nut',
        iconBgColor: 'bg-amber-200',
        iconTextColor: 'text-amber-900',
      },
    ],
  },
  {
    id: 'poultry',
    name: 'Poultry',
    badge: 'CLASSIC & HERBAL',
    tagline: 'Classic rubs, brines, and delicate spices.',
    description: 'Perfect herbs and base elements to render chicken and turkey succulent and deeply fragrant.',
    image: '/src/assets/images/poultry_seasoning_1784062724291.jpg',
    seasonings: [
      {
        id: 'sage',
        name: 'Rubbed Sage',
        category: 'poultry',
        profile: 'Velvety & Camphor',
        description: 'The definitive poultry herb. Delivers a nostalgic, comforting roast aroma that permeates the meat.',
        iconName: 'Compass',
        iconBgColor: 'bg-teal-100',
        iconTextColor: 'text-teal-800',
      },
      {
        id: 'lemon_pepper_rub',
        name: 'Lemon Pepper Rub',
        category: 'poultry',
        profile: 'Zesty & Sharp',
        description: 'A classic rub that marries cracked black pepper with citric rind oils for a sunny, punchy bite.',
        iconName: 'Sparkle',
        iconBgColor: 'bg-lime-100',
        iconTextColor: 'text-lime-800',
      },
      {
        id: 'sweet_paprika_rub',
        name: 'Sweet Paprika',
        category: 'poultry',
        profile: 'Sweet & Warm',
        description: 'Yields a stunning golden-red color on chicken skin or thighs while adding mild, pleasant sweetness.',
        iconName: 'Sun',
        iconBgColor: 'bg-rose-100',
        iconTextColor: 'text-rose-800',
      },
      {
        id: 'salted_butter_basting',
        name: 'Herb Butter Baste',
        category: 'poultry',
        profile: 'Rich & Lactose',
        description: 'Basting melted butter infused with poultry seasonings keeps breast cuts tender and intensely juicy.',
        iconName: 'Milky',
        iconBgColor: 'bg-yellow-200',
        iconTextColor: 'text-yellow-900',
      },
    ],
  },
];

export const RECIPES: RecipeItem[] = [
  {
    id: 'garlic_ribeye',
    title: 'Garlic Butter Ribeye Steak',
    tagline: 'The ultimate golden-crusted steak experience.',
    category: 'beef',
    prepTime: '15 mins',
    cookTime: '10 mins',
    servings: 2,
    difficulty: 'Medium',
    image: '/src/assets/images/beef_seasoning_1784062685307.jpg',
    description: 'A thick, dry-brined ribeye seared hot in a cast-iron skillet, basted generously with melted butter, crushed garlic, and fresh rosemary.',
    ingredients: [
      { name: 'Ribeye Steak (1.5" thick)', amount: '1 lb' },
      { name: 'Coarse Black Pepper', amount: '1 tbsp' },
      { name: 'Maldon Sea Salt Flakes', amount: '2 tsp' },
      { name: 'Unsalted Butter', amount: '4 tbsp' },
      { name: 'Fresh Rosemary Sprigs', amount: '3 pieces' },
      { name: 'Garlic Powder', amount: '1 tsp' },
      { name: 'Smoked Paprika (for dry rub)', amount: '1/2 tsp' },
    ],
    seasoningsUsed: ['smoked_paprika', 'rosemary', 'coarse_black_pepper', 'garlic_powder'],
    steps: [
      'Take the ribeye out of the fridge 30 minutes before cooking. Pat it completely dry with paper towels to ensure a beautiful crust.',
      'Generously season all sides of the ribeye with salt, coarse black pepper, garlic powder, and a light touch of smoked paprika.',
      'Preheat your cast-iron skillet over high heat until smoking. Add a high-smoke-point oil (like avocado oil) to coat the pan bottom.',
      'Lay the steak in the skillet away from you. Sear without moving for 2 minutes on each side to build a rich brown crust.',
      'Reduce the heat slightly, then toss in the butter, rosemary sprigs, and smashed garlic cloves. Tilt the skillet and spoon the foamy basted butter over the steak continuously for 2 minutes.',
      'Remove steak once internal temp reaches 130°F (for Medium-Rare). Let it rest on a cutting board for 8 minutes before slicing.',
    ],
    nutrition: {
      calories: '750 kcal',
      protein: '52g',
      carbs: '2g',
      fat: '58g',
    },
  },
  {
    id: 'lemon_dill_salmon',
    title: 'Crispy Lemon Dill Salmon Fillet',
    tagline: 'Fresh, bright, and perfectly flaky ocean fish.',
    category: 'seafood',
    prepTime: '10 mins',
    cookTime: '12 mins',
    servings: 2,
    difficulty: 'Easy',
    image: '/src/assets/images/fish_seafood_1784062694000.jpg',
    description: 'Crispy-skinned pan-roasted salmon fillet with a beautiful crust of sea salt, finished with fresh fragrant dill leaves and bright lemon zest oil.',
    ingredients: [
      { name: 'Salmon Fillets (skin on)', amount: '2 pieces' },
      { name: 'Fresh Dill (chopped)', amount: '3 tbsp' },
      { name: 'Lemon (for zest and juice)', amount: '1 piece' },
      { name: 'Maldon Sea Salt Flakes', amount: '1 tsp' },
      { name: 'Extra Virgin Olive Oil', amount: '2 tbsp' },
      { name: 'Cayenne Pepper', amount: '1 pinch' },
    ],
    seasoningsUsed: ['dill', 'lemon_zest', 'sea_salt_flakes', 'cayenne_pepper'],
    steps: [
      'Pat salmon dry with paper towels. Score the skin lightly with a sharp knife to prevent buckling, and season both sides with sea salt and a touch of cayenne.',
      'Heat olive oil in a non-stick pan over medium-high heat until shimmer. Place salmon skin-side down, pressing gently with a spatula for 15 seconds.',
      'Cook skin-side down for 7 minutes, letting the skin become extremely crisp and the heat travel up the fillet.',
      'Carefully flip the salmon and cook the flesh side for just 2 to 3 minutes, preserving a tender and juicy medium-rare center.',
      'Grate fresh lemon zest over the fillets, squeeze fresh lemon juice, and shower with plenty of chopped fresh dill.',
      'Plate skin-side up and serve immediately with extra lemon wedges.',
    ],
    nutrition: {
      calories: '420 kcal',
      protein: '34g',
      carbs: '1g',
      fat: '28g',
    },
  },
  {
    id: 'arugula_balsamic_salad',
    title: 'Arugula Salad with Balsamic Glaze',
    tagline: 'An elegant, tangy organic salad in minutes.',
    category: 'greens',
    prepTime: '8 mins',
    cookTime: '0 mins',
    servings: 2,
    difficulty: 'Easy',
    image: '/src/assets/images/leafy_greens_1784062701760.jpg',
    description: 'A peppery, crisp bowl of fresh arugula leaves tossed with premium toasted sesame seeds, whipped Dijon-balsamic dressing, and sea salt flakes.',
    ingredients: [
      { name: 'Fresh Baby Arugula', amount: '5 oz' },
      { name: 'Balsamic Glaze (aged)', amount: '2 tbsp' },
      { name: 'Toasted Sesame Seeds', amount: '1 tbsp' },
      { name: 'Dijon Mustard', amount: '1 tsp' },
      { name: 'Extra Virgin Olive Oil', amount: '3 tbsp' },
      { name: 'Parmigiano-Reggiano', amount: '2 oz' },
    ],
    seasoningsUsed: ['balsamic_vinegar', 'toasted_sesame', 'dijon_mustard', 'nutritional_yeast'],
    steps: [
      'In a small bowl, whisk together the extra virgin olive oil, Dijon mustard, a drop of balsamic, and a pinch of salt until creamy and emulsified.',
      'Toast your sesame seeds in a dry pan over low heat for 2 minutes until golden and intensely aromatic. Let cool.',
      'Wash and thoroughly dry the baby arugula leaves (wet greens dilute dressings).',
      'Drizzle the creamy Dijon dressing over the arugula in a large salad bowl and toss gently with your hands or tongs.',
      'Shave thin ribbons of Parmigiano-Reggiano cheese over the greens.',
      'Drizzle aged sweet balsamic glaze in a decorative zigzag pattern, then scatter toasted sesame seeds and nutritional yeast on top.',
    ],
    nutrition: {
      calories: '280 kcal',
      protein: '6g',
      carbs: '8g',
      fat: '25g',
    },
  },
  {
    id: 'roasted_roots',
    title: 'Honey Maple Glazed Root Veggies',
    tagline: 'Sweet, caramelized, and comforting roasted roots.',
    category: 'root_veg',
    prepTime: '15 mins',
    cookTime: '30 mins',
    servings: 4,
    difficulty: 'Easy',
    image: '/src/assets/images/root_vegetables_1784062711149.jpg',
    description: 'Cubed sweet potatoes, carrots, and parsnips roasted with fresh thyme, ground cumin, and a rich, crispy maple syrup glaze.',
    ingredients: [
      { name: 'Sweet Potatoes (cubed)', amount: '2 medium' },
      { name: 'Heirloom Carrots (halved)', amount: '4 pieces' },
      { name: 'Parsnips (sliced)', amount: '2 pieces' },
      { name: 'Fresh Thyme Sprigs', amount: '6 pieces' },
      { name: 'Pure Maple Syrup', amount: '2 tbsp' },
      { name: 'Ground Cumin', amount: '1/2 tsp' },
      { name: 'Olive Oil', amount: '3 tbsp' },
      { name: 'Grated Nutmeg', amount: '1 pinch' },
    ],
    seasoningsUsed: ['thyme', 'maple_syrup', 'cumin', 'nutmeg'],
    steps: [
      'Preheat your oven to 425°F (220°C). High heat is essential to caramelize the starches quickly.',
      'Peel and cut all sweet potatoes, carrots, and parsnips into uniform 1-inch chunks to ensure even cooking.',
      'In a large mixing bowl, toss the vegetables with olive oil, ground cumin, a tiny pinch of fresh grated nutmeg, sea salt, and fresh thyme leaves.',
      'Spread the vegetables in a single layer on a large baking sheet. Do not crowd them, or they will steam instead of roasting.',
      'Roast in the preheated oven for 20 minutes until tender. Take the pan out, drizzle pure maple syrup over the hot roots, and toss them gently with a spatula.',
      'Return to the oven for an additional 10 minutes until the edges are beautifully browned, crispy, and glazed.',
    ],
    nutrition: {
      calories: '210 kcal',
      protein: '3g',
      carbs: '38g',
      fat: '7g',
    },
  },
  {
    id: 'sage_chicken_breast',
    title: 'Sage & Herb Butter Roasted Chicken',
    tagline: 'Succulent, skin-on chicken breast basted in wild sage.',
    category: 'poultry',
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: 2,
    difficulty: 'Easy',
    image: '/src/assets/images/poultry_seasoning_1784062724291.jpg',
    description: 'Juicy roasted chicken breast with crispy golden skin, baked with a fragrant lemon pepper rub, basted in melted butter and fresh sage leaves.',
    ingredients: [
      { name: 'Bone-in, Skin-on Chicken Breasts', amount: '2 pieces' },
      { name: 'Fresh Sage Leaves', amount: '8 pieces' },
      { name: 'Lemon Pepper Rub', amount: '1 tbsp' },
      { name: 'Unsalted Butter', amount: '3 tbsp' },
      { name: 'Sweet Paprika', amount: '1 tsp' },
      { name: 'Garlic Cloves', amount: '4 cloves' },
    ],
    seasoningsUsed: ['sage', 'lemon_pepper_rub', 'sweet_paprika_rub', 'salted_butter_basting'],
    steps: [
      'Pat chicken dry. Loosen the skin carefully with your fingers, and slide 2 fresh sage leaves directly under the skin of each breast.',
      'Season the skin and underside generously with lemon-pepper rub, sea salt, and sweet paprika for a golden color.',
      'Preheat your oven to 400°F (200°C). Heat 1 tablespoon of olive oil in an oven-safe skillet over medium-high heat.',
      'Place the chicken skin-side down in the hot skillet. Sear for 4 minutes until the skin is golden-brown and crisp.',
      'Flip the chicken breast, add butter, remaining sage leaves, and smashed garlic cloves to the skillet. Baste the chicken skin with the foaming butter.',
      'Transfer the whole skillet directly into the oven. Roast for 15 minutes or until the internal temperature reaches 165°F (74°C). Rest for 5 minutes before carving.',
    ],
    nutrition: {
      calories: '490 kcal',
      protein: '41g',
      carbs: '2g',
      fat: '33g',
    },
  },
];

export const INITIAL_PANTRY: string[] = [
  'Smoked Paprika',
  'Coarse Black Pepper',
  'Garlic Powder',
  'Lemon Zest',
  'Maldon Sea Salt',
  'Fresh Thyme',
  'Fresh Rosemary',
];
